window.PAPER_GRAPH_DATA = {
  "meta": {
    "schema_version": 1,
    "generated_at": "2026-08-20T01:23:35Z",
    "approved_papers": 36,
    "new_nodes": 34
  },
  "nodes": [
    {
      "id": "V_JEPA2",
      "name": "V-JEPA 2：自监督视频模型实现理解、预测与规划",
      "type": "paper",
      "description": "通过大规模视频自监督预训练与少量机器人交互数据后训练，V-JEPA 2 在潜在空间中学习环境动态，并把表征用于理解、预测和机器人规划。",
      "group_id": "jepa",
      "group_name": "JEPA 联合嵌入预测架构",
      "tags": [
        "JEPA",
        "视频世界模型",
        "机器人规划"
      ],
      "paper_id": "arxiv:2506.09985",
      "title_en": "V-JEPA 2: Self-Supervised Video Models Enable Understanding, Prediction and Planning",
      "authors": [
        "Mido Assran",
        "Adrien Bardes",
        "David Fan",
        "Quentin Garrido",
        "Russell Howes",
        "Mojtaba Komeili",
        "Koustuv Sinha",
        "Yann LeCun",
        "Michael Rabbat",
        "Nicolas Ballas"
      ],
      "affiliations": [
        "Meta FAIR"
      ],
      "venue": "arXiv",
      "publication_status": "preprint",
      "published_at": "2025-06-11T17:57:09Z",
      "updated_at": "2025-06-11T17:57:09Z",
      "source_kind": "arxiv",
      "source_url": "https://arxiv.org/abs/2506.09985",
      "pdf_url": "https://arxiv.org/pdf/2506.09985",
      "contribution_zh": "把 JEPA 视频表征扩展到动作条件世界模型，并展示跨实验室的零样本机械臂目标图像规划。",
      "review_status": "approved",
      "reviewed_at": "2026-08-12T00:00:00Z",
      "relevance_score": 10.0
    },
    {
      "id": "V_JEPA2_1",
      "name": "V-JEPA 2.1：释放视频自监督学习中的密集特征",
      "type": "paper",
      "description": "V-JEPA 2.1 通过密集预测损失、深层自监督和多模态 tokenizer，兼顾局部时空表征与全局场景理解。",
      "group_id": "jepa",
      "group_name": "JEPA 联合嵌入预测架构",
      "tags": [
        "JEPA",
        "视频表征",
        "机器人感知"
      ],
      "paper_id": "arxiv:2603.14482",
      "title_en": "V-JEPA 2.1: Unlocking Dense Features in Video Self-Supervised Learning",
      "authors": [
        "Lorenzo Mur-Labadia",
        "Matthew Muckley",
        "Amir Bar",
        "Mido Assran",
        "Koustuv Sinha",
        "Mike Rabbat",
        "Yann LeCun",
        "Nicolas Ballas",
        "Adrien Bardes"
      ],
      "affiliations": [
        "Meta FAIR"
      ],
      "venue": "arXiv",
      "publication_status": "preprint",
      "published_at": "2026-03-15T17:02:40Z",
      "updated_at": "2026-03-15T17:02:40Z",
      "source_kind": "arxiv",
      "source_url": "https://arxiv.org/abs/2603.14482",
      "pdf_url": "https://arxiv.org/pdf/2603.14482",
      "contribution_zh": "在视频理解、深度估计、机器人抓取和导航任务上验证了密集 JEPA 表征的迁移能力。",
      "review_status": "approved",
      "reviewed_at": "2026-08-12T00:00:00Z",
      "relevance_score": 9.0
    },
    {
      "id": "paper_2607_11689",
      "name": "从世界动作模型到具身大脑：开放世界物理智能路线图",
      "type": "paper",
      "description": "文章梳理世界动作模型、视觉语言动作策略与世界模型的关系，并提出由模型、物理执行框架、共享接口和闭环训练组成的开放世界物理智能路线图。",
      "group_id": "action_ground",
      "group_name": "动作对齐",
      "tags": [
        "世界动作模型",
        "Physical AI",
        "具身智能"
      ],
      "paper_id": "arxiv:2607.11689",
      "title_en": "From World Action Models to Embodied Brains: A Roadmap for Open-World Physical Intelligence",
      "authors": [
        "Yuanzhi Liang",
        "Xufeng Zhan",
        "Haibin Huang",
        "Chi Zhang",
        "Xuelong Li"
      ],
      "affiliations": [],
      "venue": "arXiv",
      "publication_status": "preprint",
      "published_at": "2026-07-13T15:22:56Z",
      "updated_at": "2026-07-13T15:22:56Z",
      "source_kind": "arxiv",
      "source_url": "https://arxiv.org/abs/2607.11689",
      "pdf_url": "https://arxiv.org/pdf/2607.11689",
      "contribution_zh": "把碎片化的模型角色、动作空间、任务协议和系统接口归纳为可组合的具身智能技术栈。",
      "review_status": "approved",
      "reviewed_at": "2026-08-12T00:00:00Z",
      "relevance_score": 10.0,
      "degree": 0,
      "composite_weight": 0.1
    },
    {
      "id": "paper_2608_17542",
      "name": "No Gaussian Required: Contrastive Inverse Dynamics for JEPA World Models",
      "type": "paper",
      "description": "Joint-Embedding Predictive Architectures (JEPAs) learn world models by predicting future embeddings, but the objective admits a trivial solution of a constant encoder, so every practical system adds an anti-collapse mechanism (LeCun, 2022; Assran et al., 2023; Bardes et al., 2022; 2024). LeWorldModel (LeWM) prevents collapse with SIGReg, a regularizer that forces the latent distribution to match an isotropic Gaussian: the representation is stabilized by prescribing what it must look like, independently of the environment it models. We argue that the anti-collapse pressure can instead come from the transition data itself. Action-Contrastive Masked Transition Modeling (AC-MTM) keeps LeWM's forward latent-prediction objective and adds a training-only inverse-dynamics head trained with Action-NCE: each latent transition must identify the action that produced it among the other actions in the batch, a discrimination task that a collapsed encoder provably fails. The inverse branch is discard",
      "group_id": "jepa",
      "group_name": "JEPA 联合嵌入预测架构",
      "tags": [
        "cs.LG",
        "cs.AI",
        "world model",
        "world models",
        "jepa"
      ],
      "paper_id": "arxiv:2608.17542",
      "title_en": "No Gaussian Required: Contrastive Inverse Dynamics for JEPA World Models",
      "authors": [
        "Jack Boylan",
        "Chris Hokamp"
      ],
      "affiliations": [],
      "venue": "arXiv",
      "publication_status": "preprint",
      "published_at": "2026-08-18T09:03:35Z",
      "updated_at": "2026-08-18T09:03:35Z",
      "source_kind": "arxiv",
      "source_url": "https://arxiv.org/abs/2608.17542",
      "pdf_url": "https://arxiv.org/pdf/2608.17542v1",
      "contribution_zh": "",
      "review_status": "approved",
      "reviewed_at": "2026-08-20T00:49:55Z",
      "relevance_score": 18.75,
      "degree": 0,
      "composite_weight": 0.1875
    },
    {
      "id": "paper_2608_16287",
      "name": "SCALE: State-Calibrated Latent Embeddings for JEPA Planning in the Right Geometry",
      "type": "paper",
      "description": "Joint-embedding predictive world models plan by scoring predicted terminal embeddings against a goal embedding using a cost defined on the representation itself. Two prominent strategies for obtaining non-collapsed representations are to inherit a pretrained feature space, as in DINO-WM, and to learn an embedding end to end with anti-collapse regularization, as in LeWorldModel (LeWM) with SIGReg. These strategies show complementary strengths across tasks. Although task-relevant state is decodable from the full embeddings of both models, DINO-WM's leading principal components usually retain substantially more state information than LeWM's. Because Euclidean planning costs are dominated by high-variance directions, this difference affects how strongly state can influence candidate selection. We propose SCALE (State-CAlibrated Latent Embeddings) to give the end-to-end LeWM representation the favorable geometric property observed in DINO-WM. SCALE induces this property by correlating sampl",
      "group_id": "jepa",
      "group_name": "JEPA 联合嵌入预测架构",
      "tags": [
        "cs.LG",
        "world model",
        "world models",
        "jepa"
      ],
      "paper_id": "arxiv:2608.16287",
      "title_en": "SCALE: State-Calibrated Latent Embeddings for JEPA Planning in the Right Geometry",
      "authors": [
        "Jiaming Hu",
        "Yan Zheng",
        "Tian Wang"
      ],
      "affiliations": [],
      "venue": "arXiv",
      "publication_status": "preprint",
      "published_at": "2026-08-17T08:58:55Z",
      "updated_at": "2026-08-17T08:58:55Z",
      "source_kind": "arxiv",
      "source_url": "https://arxiv.org/abs/2608.16287",
      "pdf_url": "https://arxiv.org/pdf/2608.16287v1",
      "contribution_zh": "",
      "review_status": "approved",
      "reviewed_at": "2026-08-20T00:49:55Z",
      "relevance_score": 16.25,
      "degree": 0,
      "composite_weight": 0.1625
    },
    {
      "id": "paper_2608_17959",
      "name": "Towards Zero-Shot Task Transfer with Neurosymbolic World Models",
      "type": "paper",
      "description": "State-of-the-art model-based reinforcement learning methods learn neural world models that allow policy improvement by planning in a latent space, without assumptions on the structure of the underlying environment. While expressive, these models are generally task-dependent: they learn uninterpretable latent representations that are tied to the training task and thus hard to generalize to new tasks. In this work, we present a novel world model formulation where the reward prediction only depends on a subset of structured, symbolic components of the whole latent state. Decoupling observation reconstruction and reward prediction allows us to learn world models that can adapt zero-shot, i.e. without further environment interactions, to new reward functions defined over the same symbolic state space. We discuss the main advantages and challenges of learning these neurosymbolic world models and demonstrate the strong generalisation properties of our approach over purely neural methods.",
      "group_id": "latent_wm",
      "group_name": "隐空间动力学与规划",
      "tags": [
        "cs.AI",
        "cs.LG",
        "world model",
        "world models"
      ],
      "paper_id": "arxiv:2608.17959",
      "title_en": "Towards Zero-Shot Task Transfer with Neurosymbolic World Models",
      "authors": [
        "Isidoro Tamassia",
        "Lennert De Smet",
        "Giuseppe Marra"
      ],
      "affiliations": [],
      "venue": "arXiv",
      "publication_status": "preprint",
      "published_at": "2026-08-18T16:12:40Z",
      "updated_at": "2026-08-18T16:12:40Z",
      "source_kind": "arxiv",
      "source_url": "https://arxiv.org/abs/2608.17959",
      "pdf_url": "https://arxiv.org/pdf/2608.17959v1",
      "contribution_zh": "",
      "review_status": "approved",
      "reviewed_at": "2026-08-20T00:49:55Z",
      "relevance_score": 12.5,
      "degree": 0,
      "composite_weight": 0.125
    },
    {
      "id": "paper_2608_17956",
      "name": "An Omitted Mode Is a Rare Rule: The Sampling-Verification Danger Law in Continuous Code World Models",
      "type": "paper",
      "description": "In the Code World Model paradigm an LLM synthesizes an executable world model that a classical planner searches, and the model is accepted when it reproduces sampled transitions. We ask what that acceptance certifies in continuous control. We define the pipeline's danger as an expected risk and isolate its exact factor: the probability that N i.i.d. gate rollouts all miss a critical event of probability r is exactly (1-r)^N; an independent acceptance sample adds its budget to the exponent. On three hybrid instruments the accepted mode-blind model is exploited: the planner is pinned at the mode boundary at a regret of nearly the whole attainable return. We prove a localization budget, valid at boundary points: models with Lipschitz constant at most L differing by eta at a point disagree above tolerance eps on a region of volume at least kappa((eta-eps)/L)^(d+m); the discontinuous reset modes studied pay no such budget. With real LLM synthesis, GPT-5.x repairs an omitted 1D clamp in 105 ",
      "group_id": "latent_wm",
      "group_name": "隐空间动力学与规划",
      "tags": [
        "cs.LG",
        "cs.AI",
        "eess.SY",
        "world model",
        "world models"
      ],
      "paper_id": "arxiv:2608.17956",
      "title_en": "An Omitted Mode Is a Rare Rule: The Sampling-Verification Danger Law in Continuous Code World Models",
      "authors": [
        "Javier Aguilar Martín"
      ],
      "affiliations": [],
      "venue": "arXiv",
      "publication_status": "preprint",
      "published_at": "2026-08-18T16:09:51Z",
      "updated_at": "2026-08-18T16:09:51Z",
      "source_kind": "arxiv",
      "source_url": "https://arxiv.org/abs/2608.17956",
      "pdf_url": "https://arxiv.org/pdf/2608.17956v1",
      "contribution_zh": "",
      "review_status": "approved",
      "reviewed_at": "2026-08-20T00:49:55Z",
      "relevance_score": 12.5,
      "degree": 0,
      "composite_weight": 0.125
    },
    {
      "id": "paper_2608_17163",
      "name": "Q-Learning With World Models",
      "type": "paper",
      "description": "Off-policy reinforcement learning (RL) has become increasingly sample-efficient, enabling applications such as RL fine-tuning of Vision-Language-Action models into reliable, high-performing policies. World models offer a further lever for sample efficiency, as they predict state changes rather than actions alone, but their success has largely been confined to supervised policy learning. Prior model-based RL methods often optimize the policy or value function directly on imagined rollouts, which is prone to compounding bias and struggles to scale to large, high-dimensional problems such as real-world robotics, a problem that worsens with task horizon and visual complexity. In this work, we instead ask whether we can leverage world models directly on top of standard Q-learning to improve performance, while remaining trained and grounded in the real, online setting. We propose QWM, a framework that leverages world models to perform test-time search over imagined trajectories on top of Q-l",
      "group_id": "latent_wm",
      "group_name": "隐空间动力学与规划",
      "tags": [
        "cs.LG",
        "cs.AI",
        "world model",
        "world models",
        "vision-language-action",
        "robotics",
        "robot"
      ],
      "paper_id": "arxiv:2608.17163",
      "title_en": "Q-Learning With World Models",
      "authors": [
        "Perry Dong",
        "Yueru Jia",
        "Chelsea Finn",
        "Dorsa Sadigh"
      ],
      "affiliations": [],
      "venue": "arXiv",
      "publication_status": "preprint",
      "published_at": "2026-08-17T22:00:42Z",
      "updated_at": "2026-08-17T22:00:42Z",
      "source_kind": "arxiv",
      "source_url": "https://arxiv.org/abs/2608.17163",
      "pdf_url": "https://arxiv.org/pdf/2608.17163v1",
      "contribution_zh": "",
      "review_status": "approved",
      "reviewed_at": "2026-08-20T00:49:55Z",
      "relevance_score": 19.0,
      "degree": 1,
      "composite_weight": 0.19
    },
    {
      "id": "paper_2608_16651",
      "name": "Orbit-Planner: Towards Latent World Models for On-Orbit Obstacle Avoidance of Satellite Agents",
      "type": "paper",
      "description": "Satellite agents for on-orbit navigation tasks need to predict collision risks using limited onboard observations. However, conventional planners often rely on predefined maps and fixed environmental assumptions, limiting their adaptability in dynamic on-orbit scenarios. In this paper, we propose Orbit-Planner, a two-stage latent world model for on-orbit obstacle avoidance. Orbit-Planner learns action-conditioned spacecraft dynamics to perform future-state rollouts in latent space, and introduces a Physics Probe to decode physical state changes from imagined latent trajectories. Experiments demonstrate that Orbit-Planner can perform long-horizon latent rollouts and recover physical states from imagined trajectories. In closed-loop obstacle-avoidance navigation in Isaac Sim, it attains a success rate of 91.7%. Code is available at https://github.com/ZhijianLi2003/Orbit_Planner.",
      "group_id": "latent_wm",
      "group_name": "隐空间动力学与规划",
      "tags": [
        "cs.RO",
        "cs.AI",
        "world model",
        "world models",
        "action-conditioned"
      ],
      "paper_id": "arxiv:2608.16651",
      "title_en": "Orbit-Planner: Towards Latent World Models for On-Orbit Obstacle Avoidance of Satellite Agents",
      "authors": [
        "Zhijian Li",
        "Chao Ren",
        "Peijin Wang",
        "Xian Sun"
      ],
      "affiliations": [],
      "venue": "AP-GARSS 2026",
      "publication_status": "accepted",
      "published_at": "2026-08-17T14:49:07Z",
      "updated_at": "2026-08-17T14:49:07Z",
      "source_kind": "arxiv",
      "source_url": "https://arxiv.org/abs/2608.16651",
      "pdf_url": "https://arxiv.org/pdf/2608.16651v1",
      "contribution_zh": "",
      "review_status": "approved",
      "reviewed_at": "2026-08-20T00:49:55Z",
      "relevance_score": 15.5,
      "degree": 0,
      "composite_weight": 0.155
    },
    {
      "id": "paper_2608_16859",
      "name": "HarnessEval-W: Agentifying the Evaluation of Visual Worlds",
      "type": "paper",
      "description": "A benchmark should deliver more than a scalar score: what makes an evaluation trustworthy is the reasoning that justifies the score. This is especially critical for world models, where judging a rollout requires understanding whether physics, causality, and world state evolve correctly. Humans spot such violations naturally, yet no existing benchmark automates this capability: metrics are computed brute-force, leaving no reasoning chain that can be examined or verified. We introduce HarnessEval-W, an agentified evaluation pipeline that brings the harness paradigm from the LLM ecosystem to world model benchmarking. Rather than applying a fixed rubric, HarnessEval-W interprets the context of each evaluation case, decomposes the evaluation question into measurable subproblems, and spawns specialized sub-agents, each equipped with tailored context and diagnostic tools to reason over its own subproblem. The parent agent then validates the gathered evidence and summarizes it into the final v",
      "group_id": "gen_simulator",
      "group_name": "生成式世界模拟",
      "tags": [
        "cs.CV",
        "world model",
        "world models"
      ],
      "paper_id": "arxiv:2608.16859",
      "title_en": "HarnessEval-W: Agentifying the Evaluation of Visual Worlds",
      "authors": [
        "Weiliang Chen",
        "Haowen Sun",
        "Jun Gao",
        "Jiawei Chi",
        "Hanyang Wang",
        "Qiyu Dai",
        "Yihao Li",
        "Hao Li",
        "Jingnan Gao",
        "Yi-Hsin Hung",
        "Xingzhuo Guo",
        "Shangchen Miao",
        "Zhiyuan Shi",
        "Xiang Li",
        "Fengrui Tian",
        "Weihua Du",
        "Ziqi Huang",
        "Shenyuan Gao",
        "Siqiao Huang",
        "Mingyu Liu",
        "Yifei Li",
        "Shizun Wang",
        "Xi Wang",
        "Tianqi Zhang",
        "Xue Luo",
        "Xiyin Ren",
        "Jinshan Ren",
        "Xiaoyang Shen",
        "Xiaobo Hu",
        "Zhiyang Dou",
        "Mingyu Ding",
        "Yichao Yan",
        "Xinchao Wang",
        "Yizhou Wang",
        "Shilong Liu",
        "Wenzhao Zheng",
        "Yueqi Duan",
        "Yuan Gong",
        "Ziwei Liu",
        "Ming-Yu Liu",
        "Jialong Wu",
        "Jiangran Lyu",
        "Fangfu Liu"
      ],
      "affiliations": [],
      "venue": "arXiv",
      "publication_status": "preprint",
      "published_at": "2026-08-17T17:43:24Z",
      "updated_at": "2026-08-17T17:43:24Z",
      "source_kind": "arxiv",
      "source_url": "https://arxiv.org/abs/2608.16859",
      "pdf_url": "https://arxiv.org/pdf/2608.16859v1",
      "contribution_zh": "",
      "review_status": "approved",
      "reviewed_at": "2026-08-20T00:49:55Z",
      "relevance_score": 10.0,
      "degree": 2,
      "composite_weight": 0.1
    },
    {
      "id": "paper_2608_16829",
      "name": "CaliBench: Are the Stochastic Dynamics of Video World Models Physically Calibrated?",
      "type": "paper",
      "description": "Video world models approximate the stochastic distribution of physical outcomes through generative sampling, but existing benchmarks score individual generations or compare distributions coarsely over a whole dataset, leaving the fine-grained aleatoric uncertainty of specific phenomena untested. We introduce CaliBench, which scores outcomes in a physically interpretable discrete space - a bin index, a die face, a suit, a colour - rather than a learned feature space such as in FID, so the distance from a known reference distribution is measured directly. We curate outcome spaces whose reference is known in closed form (binomial Galton boards, Bernoulli forks, uniform dice/cards/lottery, a skewed European-roulette colour), enabling an exact calibration test. We decompose performance into two orthogonal axes that a single accuracy metric conflates: scorability, the fraction of generations yielding a scoreable outcome, and calibration, the total variation distance from the reference on tha",
      "group_id": "gen_simulator",
      "group_name": "生成式世界模拟",
      "tags": [
        "cs.LG",
        "cs.AI",
        "world model",
        "world models"
      ],
      "paper_id": "arxiv:2608.16829",
      "title_en": "CaliBench: Are the Stochastic Dynamics of Video World Models Physically Calibrated?",
      "authors": [
        "Jonathan Sadeghi",
        "Jenny Seidenschwarz",
        "Jesse Allardice",
        "Sirish Srinivasan",
        "Benjamin Graham",
        "Jeffrey Hawke"
      ],
      "affiliations": [],
      "venue": "arXiv",
      "publication_status": "preprint",
      "published_at": "2026-08-17T17:14:50Z",
      "updated_at": "2026-08-17T17:14:50Z",
      "source_kind": "arxiv",
      "source_url": "https://arxiv.org/abs/2608.16829",
      "pdf_url": "https://arxiv.org/pdf/2608.16829v1",
      "contribution_zh": "",
      "review_status": "approved",
      "reviewed_at": "2026-08-20T00:49:55Z",
      "relevance_score": 12.5,
      "degree": 0,
      "composite_weight": 0.125
    },
    {
      "id": "paper_2608_16354",
      "name": "DriveCache: Action-Aware Caching for Driving World Model Inference",
      "type": "paper",
      "description": "Driving video generation models support autonomous-driving development by predicting controllable future scenes for simulation, planning evaluation, and offline data generation. Diffusion-based driving generators repeatedly evaluate large backbones across denoising steps, which limits generation throughput. Existing diffusion acceleration methods reduce this cost, but general-purpose designs omit driving signals available before generation, such as ego speed and planned trajectories. Experiments across driving motions show that cache tolerance varies with ego translation and rotation, denoising progress, and consecutive reuse length. We propose DriveCache, a training-free, action-aware controller that uses planned motion to allocate reuse across scenes and dynamic programming to place it across denoising steps under a calibrated response budget. A causal drift check refreshes features and replans the remaining schedule when generation departs from calibration. Across three generator co",
      "group_id": "gen_simulator",
      "group_name": "生成式世界模拟",
      "tags": [
        "cs.AI",
        "cs.CV",
        "world model",
        "video generation"
      ],
      "paper_id": "arxiv:2608.16354",
      "title_en": "DriveCache: Action-Aware Caching for Driving World Model Inference",
      "authors": [
        "Jianchun Yang",
        "Jian Liang",
        "Xianda Guo",
        "Pinhan Fu",
        "Yanlun Peng",
        "Conglang Zhang",
        "Wenke Huang",
        "Mang Ye"
      ],
      "affiliations": [],
      "venue": "arXiv",
      "publication_status": "preprint",
      "published_at": "2026-08-17T10:04:49Z",
      "updated_at": "2026-08-17T10:04:49Z",
      "source_kind": "arxiv",
      "source_url": "https://arxiv.org/abs/2608.16354",
      "pdf_url": "https://arxiv.org/pdf/2608.16354v1",
      "contribution_zh": "",
      "review_status": "approved",
      "reviewed_at": "2026-08-20T00:49:55Z",
      "relevance_score": 8.25,
      "degree": 0,
      "composite_weight": 0.0825
    },
    {
      "id": "paper_2608_16234",
      "name": "GaussianDWM++: Language-Grounded 3D Gaussian Driving World Model for Unified Scene Understanding, Editing, and Multi-Modal Generation",
      "type": "paper",
      "description": "Driving World Models (DWMs) have recently advanced rapidly with generative models, yet most existing methods mainly focus on conditional scene generation and lack explicit 3D scene understanding, language-grounded reasoning, and controllable 4D editing capabilities. Moreover, commonly used point cloud, occupancy, or BEV representations make it difficult to achieve fine-grained alignment between textual information and the underlying 3D scene structure. To address these limitations, we propose a foundation-feature Gaussian driving world model that unifies scene understanding, language-grounded reasoning, controllable 4D editing, and multi-modal generation within a single framework. Specifically, we introduce a foundation-feature Gaussian tokenizer that directly distills Qwen/SigLIP visual-language features into 3D Gaussian primitives, building a compact open-vocabulary Gaussian semantic field. We further design a geometry-aware Gaussian adapter that combines importance-aware hierarchica",
      "group_id": "gen_simulator",
      "group_name": "生成式世界模拟",
      "tags": [
        "cs.CV",
        "world model",
        "world models"
      ],
      "paper_id": "arxiv:2608.16234",
      "title_en": "GaussianDWM++: Language-Grounded 3D Gaussian Driving World Model for Unified Scene Understanding, Editing, and Multi-Modal Generation",
      "authors": [
        "Tianchen Deng",
        "Xuefeng Chen",
        "Shuang Wu",
        "Qu Chen",
        "Jiajun Zhu",
        "Bo Dai",
        "Jianfei Yang",
        "Hesheng Wang"
      ],
      "affiliations": [],
      "venue": "arXiv",
      "publication_status": "preprint",
      "published_at": "2026-08-17T08:12:56Z",
      "updated_at": "2026-08-17T08:12:56Z",
      "source_kind": "arxiv",
      "source_url": "https://arxiv.org/abs/2608.16234",
      "pdf_url": "https://arxiv.org/pdf/2608.16234v1",
      "contribution_zh": "",
      "review_status": "approved",
      "reviewed_at": "2026-08-20T00:49:55Z",
      "relevance_score": 11.25,
      "degree": 0,
      "composite_weight": 0.1125
    },
    {
      "id": "paper_2608_13546",
      "name": "Alaya-EVOKE: From Linear-Scaling Supervision to Endless World",
      "type": "paper",
      "description": "Interactive world models must support persistent memory, responsive interaction, and long-horizon generation, yet these requirements place conflicting demands on the model. Maintaining history in the denoiser context or key-value cache incurs growing cost, forcing a trade-off between session length and retained memory, while low-latency interaction relies on few-step generation whose capabilities are bounded by its teacher. Alaya-EVOKE (Evoke) addresses both limitations by externalizing persistent world state and redesigning the teacher for long-horizon interactive generation. Scene geometry is maintained in an external, camera-indexed world state bank, from which only view-relevant information is retrieved, keeping the denoiser context bounded as the session grows. Rather than treating the teacher as a fixed generator, we design it for long-horizon supervision: its sparse attention combines chunk-wise grouping, retrieval of selected distant frames, and a linear-attention global state,",
      "group_id": "interactive_wm",
      "group_name": "可交互世界模型",
      "tags": [
        "cs.CV",
        "world model",
        "world models"
      ],
      "paper_id": "arxiv:2608.13546",
      "title_en": "Alaya-EVOKE: From Linear-Scaling Supervision to Endless World",
      "authors": [
        "Yuanyang Yin",
        "Gongxuan Wang",
        "Yifan Zhan",
        "Chuanhao Li",
        "Kaipeng Zhang",
        "Feng Zhao"
      ],
      "affiliations": [],
      "venue": "arXiv",
      "publication_status": "preprint",
      "published_at": "2026-08-13T17:57:00Z",
      "updated_at": "2026-08-18T17:33:51Z",
      "source_kind": "arxiv",
      "source_url": "https://arxiv.org/abs/2608.13546",
      "pdf_url": "https://arxiv.org/pdf/2608.13546v2",
      "contribution_zh": "",
      "review_status": "approved",
      "reviewed_at": "2026-08-20T00:49:56Z",
      "relevance_score": 10.0,
      "degree": 0,
      "composite_weight": 0.1
    },
    {
      "id": "paper_2608_18077",
      "name": "Hydra-0: Action Flow for Generalist World Modeling and Control",
      "type": "paper",
      "description": "We introduce Hydra-0, a generalist world model conditioned on action flow, which represents robot actions as pixel motion. This shared visual interface enables generalist world modeling and control by learning action consequences across embodiments, tasks, environments, and video-generation backbones. Our best configuration achieves 90.4% lower robot-motion error and 60.2% lower object-motion error than our action-conditioned baseline, while supporting zero-shot composition and data-efficient adaptation. On the RoboLab benchmark, Hydra-0 achieves a Pearson correlation of r=0.96 between replayed and reference success rates. Finally, we uncover an emergent inverse mode of this interface: a world action model that predicts compatible robot motion from desired object flow transferred from a human demonstration. A trained action head maps the resulting latent features to executable actions without requiring task-specific expert robot demonstrations. Together, these results demonstrate the p",
      "group_id": "action_ground",
      "group_name": "动作对齐",
      "tags": [
        "cs.RO",
        "world model",
        "world action model",
        "robot",
        "action-conditioned"
      ],
      "paper_id": "arxiv:2608.18077",
      "title_en": "Hydra-0: Action Flow for Generalist World Modeling and Control",
      "authors": [
        "Hongyu Li",
        "Bowen Wen",
        "Xinghao Zhu",
        "Yixuan Wang",
        "Yilun Du",
        "Yunzhu Li",
        "George Konidaris",
        "Stan Birchfield",
        "Soha Pouya",
        "Chenran Li",
        "Yan Chang"
      ],
      "affiliations": [],
      "venue": "arXiv",
      "publication_status": "preprint",
      "published_at": "2026-08-18T17:59:30Z",
      "updated_at": "2026-08-18T17:59:30Z",
      "source_kind": "arxiv",
      "source_url": "https://arxiv.org/abs/2608.18077",
      "pdf_url": "https://arxiv.org/pdf/2608.18077v1",
      "contribution_zh": "",
      "review_status": "approved",
      "reviewed_at": "2026-08-20T00:49:56Z",
      "relevance_score": 15.75,
      "degree": 1,
      "composite_weight": 0.1575
    },
    {
      "id": "paper_2608_18035",
      "name": "Plug-and-Play Traffic Element Awareness for End-to-End Autonomous Driving",
      "type": "paper",
      "description": "Traffic elements such as traffic lights and road signs play a fundamental role in human driving decisions and should naturally influence end-to-end driving performance. However, existing end-to-end driving research predominantly focuses on dynamic road participants (e.g., vehicles and pedestrians), while the role of traffic elements remains largely unexplored. The community still lacks a systematic study quantifying their impact, largely because public datasets rarely provide structured traffic-element annotations and modern driving systems vary widely in architecture and training paradigm. In this work, we present the first systematic investigation of traffic element awareness for end-to-end autonomous driving. We construct a unified research infrastructure by augmenting multiple public driving datasets with comprehensive traffic-element annotations. To support diverse model families, we adopt a minimal and universal integration design that incorporates traffic-element signals into ex",
      "group_id": "action_ground",
      "group_name": "动作对齐",
      "tags": [
        "cs.CV",
        "vision-language-action"
      ],
      "paper_id": "arxiv:2608.18035",
      "title_en": "Plug-and-Play Traffic Element Awareness for End-to-End Autonomous Driving",
      "authors": [
        "Zongzheng Zhang",
        "Jijun Wang",
        "Saining Zhang",
        "Shuo Wang",
        "Yiru Wang",
        "Hai Yang",
        "Yang Chen",
        "Yuwen Heng",
        "Hao Sun",
        "Anqing Jiang",
        "Hao Zhao"
      ],
      "affiliations": [],
      "venue": "arXiv",
      "publication_status": "preprint",
      "published_at": "2026-08-18T17:29:51Z",
      "updated_at": "2026-08-18T17:29:51Z",
      "source_kind": "arxiv",
      "source_url": "https://arxiv.org/abs/2608.18035",
      "pdf_url": "https://arxiv.org/pdf/2608.18035v1",
      "contribution_zh": "",
      "review_status": "approved",
      "reviewed_at": "2026-08-20T00:49:56Z",
      "relevance_score": 5.0,
      "degree": 0,
      "composite_weight": 0.05
    },
    {
      "id": "paper_2608_17717",
      "name": "CompCPZ: Preserving Multi-Modal Intent in Language-Guided Robot Manipulation",
      "type": "paper",
      "description": "A robot asked to \"place the cup near the red plate or the blue plate\" may reach the centroid between them and appear geometrically successful, while satisfying neither disjunct of the instruction. This silent semantic failure exposes a structural limitation of language-conditioned robot policies: representations that collapse a disjunctive instruction into a single connected set cannot preserve all feasible modes, and planners that commit to one action degrade under run-time mode uncertainty. We address this limitation with CompCPZ, a sound algebraic layer that language-conditioned learning systems wrap to recover multi-modal disjunctive representation, recursively composing per-primitive constrained polynomial zonotope enclosures along the language parse tree with distribution-free conformal coverage and sub-millisecond runtime. On a closed-loop ManiSkill3 tabletop-manipulation benchmark, CompCPZ outperforms convex set baselines, multi-peak decoders, and a zero-shot vision-language-ac",
      "group_id": "action_ground",
      "group_name": "动作对齐",
      "tags": [
        "cs.RO",
        "vision-language-action",
        "robot"
      ],
      "paper_id": "arxiv:2608.17717",
      "title_en": "CompCPZ: Preserving Multi-Modal Intent in Language-Guided Robot Manipulation",
      "authors": [
        "Zhen Zhang",
        "Ahmad Hafez",
        "Peng Xie",
        "Yanliang Huang",
        "Wenyuan Wu",
        "Amr Alanwar"
      ],
      "affiliations": [],
      "venue": "arXiv",
      "publication_status": "preprint",
      "published_at": "2026-08-18T12:42:26Z",
      "updated_at": "2026-08-18T12:42:26Z",
      "source_kind": "arxiv",
      "source_url": "https://arxiv.org/abs/2608.17717",
      "pdf_url": "https://arxiv.org/pdf/2608.17717v1",
      "contribution_zh": "",
      "review_status": "approved",
      "reviewed_at": "2026-08-20T00:49:56Z",
      "relevance_score": 5.62,
      "degree": 0,
      "composite_weight": 0.0562
    },
    {
      "id": "paper_2608_17600",
      "name": "LIBERO-VIFO: Benchmarking the Capability and Safety of Visual Cue Following in Vision-Language-Action Models",
      "type": "paper",
      "description": "Visual cues are increasingly adopted to guide robot learning, but whether Vision-Language-Action (VLA) models can reliably follow authorized cues while disregarding unauthorized ones remains unclear. Existing work covers only a narrow range of cue forms and focuses on final task success, providing only a coarse assessment of cue-following capability. Treating all visual cues as authorized also leaves safety risks of unauthorized following unexplored. To address these gaps, we introduce LIBERO-VIFO, a benchmark to evaluate both the capability and safety of visual cue following in VLA models. LIBERO-VIFO defines eight visual cue families spanning diverse forms. A total of four protocols in two parts are defined: Part I tests cue understanding and authorized following, while Part II evaluates unauthorized visual cue following under language-cue conflict and empty language conditions. Evaluating seven VLA models reveals that although visual cue understanding does not reliably translate int",
      "group_id": "action_ground",
      "group_name": "动作对齐",
      "tags": [
        "cs.RO",
        "vision-language-action",
        "robot"
      ],
      "paper_id": "arxiv:2608.17600",
      "title_en": "LIBERO-VIFO: Benchmarking the Capability and Safety of Visual Cue Following in Vision-Language-Action Models",
      "authors": [
        "Zhengyan Qian",
        "Rui Yan",
        "Alex Jinpeng Wang",
        "Jinhui Tang"
      ],
      "affiliations": [],
      "venue": "arXiv",
      "publication_status": "preprint",
      "published_at": "2026-08-18T10:07:17Z",
      "updated_at": "2026-08-18T10:07:17Z",
      "source_kind": "arxiv",
      "source_url": "https://arxiv.org/abs/2608.17600",
      "pdf_url": "https://arxiv.org/pdf/2608.17600v1",
      "contribution_zh": "",
      "review_status": "approved",
      "reviewed_at": "2026-08-20T00:49:56Z",
      "relevance_score": 6.75,
      "degree": 0,
      "composite_weight": 0.0675
    },
    {
      "id": "paper_2608_17496",
      "name": "Calibrated Predictive Safety for Heterogeneous Robots: An Action-Conditioned JEPA Framework with Model-Based Safety Shields",
      "type": "paper",
      "description": "Vision-language-action policies generalize broadly but provide no execution-time guarantees; classical model-based planners respect kinematic and geometric constraints but generalize poorly. We study whether an action-conditioned Joint-Embedding Predictive Architecture (JEPA) world model can predict, before execution, both task progress and physical risk for candidate action chunks, and whether coupling these predictions to an embodiment-specific model-based safety shield yields a deployable pipeline for heterogeneous robots. We propose a receding-horizon decision pipeline: (1) a proposer produces K candidate action chunks; (2) an action-conditioned JEPA rolls each candidate forward in a frozen-encoder latent space conditioned on an embodiment embedding; (3) calibrated risk and progress heads score each rollout and report uncertainty; (4) a deterministic per-embodiment safety shield filters inadmissible candidates; (5) a fallback ladder handles empty-admissible-set cases. The learned r",
      "group_id": "action_ground",
      "group_name": "动作对齐",
      "tags": [
        "cs.RO",
        "world model",
        "vision-language-action",
        "robot",
        "jepa",
        "action-conditioned"
      ],
      "paper_id": "arxiv:2608.17496",
      "title_en": "Calibrated Predictive Safety for Heterogeneous Robots: An Action-Conditioned JEPA Framework with Model-Based Safety Shields",
      "authors": [
        "Kaiming Zhong",
        "Tianhua Liu",
        "Yue Wang"
      ],
      "affiliations": [],
      "venue": "arXiv",
      "publication_status": "preprint",
      "published_at": "2026-08-18T08:24:08Z",
      "updated_at": "2026-08-18T08:24:08Z",
      "source_kind": "arxiv",
      "source_url": "https://arxiv.org/abs/2608.17496",
      "pdf_url": "https://arxiv.org/pdf/2608.17496v1",
      "contribution_zh": "",
      "review_status": "approved",
      "reviewed_at": "2026-08-20T00:49:56Z",
      "relevance_score": 20.62,
      "degree": 0,
      "composite_weight": 0.2
    },
    {
      "id": "paper_2608_17484",
      "name": "Reuse Before You Retrieve: Diagnosing Headroom and Complementarity for Test-Time Augmentation of Embodied Multimodal Policies",
      "type": "paper",
      "description": "Frozen vision-language-action (VLA) policies are increasingly improved at test time by sampling additional policy behaviors or introducing external demonstrations. Yet there is little guidance for deciding which intervention a deployed policy actually needs. Additional sampling is useful only when better behavior already exists within the policy's stochastic rollouts and can be identified, whereas retrieval is most useful when the relevant action prior is not reliably represented by the policy. We study this decision through two measurable factors, recoverable headroom and retrieval complementarity, which characterize how much useful behavior is already available to recover and whether an external action prior fills a measurable gap. We evaluate an episode-level retry selector under retryable or parallel execution, together with retrieval across multiple frozen VLA policies and environments. The selector consistently recovers substantial latent capability across all tested VLA backbone",
      "group_id": "action_ground",
      "group_name": "动作对齐",
      "tags": [
        "cs.RO",
        "vision-language-action",
        "robot"
      ],
      "paper_id": "arxiv:2608.17484",
      "title_en": "Reuse Before You Retrieve: Diagnosing Headroom and Complementarity for Test-Time Augmentation of Embodied Multimodal Policies",
      "authors": [
        "Yuhwan Jeong",
        "Kuk-Jin Yoon"
      ],
      "affiliations": [],
      "venue": "ECCV 2026 workshop",
      "publication_status": "accepted",
      "published_at": "2026-08-18T08:11:31Z",
      "updated_at": "2026-08-18T08:11:31Z",
      "source_kind": "arxiv",
      "source_url": "https://arxiv.org/abs/2608.17484",
      "pdf_url": "https://arxiv.org/pdf/2608.17484v1",
      "contribution_zh": "",
      "review_status": "approved",
      "reviewed_at": "2026-08-20T00:49:56Z",
      "relevance_score": 5.5,
      "degree": 0,
      "composite_weight": 0.055
    },
    {
      "id": "paper_2608_17453",
      "name": "EATR-Stereo: Embodiment-Aware Routing of Paired Stereo Evidence for Humanoid Vision-Language-Action Control",
      "type": "paper",
      "description": "Long-horizon humanoid vision--language--action (VLA) control with head-mounted stereo cameras requires visual interfaces that can exploit complementary views while maintaining compatibility with pretrained representations. Existing interfaces often discard complementary stereo evidence or fuse additional observations without preserving the native primary-view pathway and adapting auxiliary information to robot embodiment. We present EATR-Stereo, an embodiment-aware token-routing framework that retains primary-view tokens and constructs primary-aligned Cross-View Auxiliary Tokens (CVATs) by querying the synchronized auxiliary-view token sequence. A body-segmented proprioceptive encoder further conditions token-wise auxiliary usage on robot configuration history, enabling selective incorporation of stereo evidence during action generation. The routed auxiliary stream augments the language and primary-visual context of a pretrained VLA while keeping its vision--language model frozen. On a",
      "group_id": "action_ground",
      "group_name": "动作对齐",
      "tags": [
        "cs.RO",
        "vision-language-action",
        "robot"
      ],
      "paper_id": "arxiv:2608.17453",
      "title_en": "EATR-Stereo: Embodiment-Aware Routing of Paired Stereo Evidence for Humanoid Vision-Language-Action Control",
      "authors": [
        "Songwei Wu",
        "Rui Zhao",
        "Fan Yang",
        "Zhongqiang Nie",
        "Zhiduo Jiang",
        "Wandong Sun",
        "Yuwei Li",
        "Yang Liu",
        "Hong Liu"
      ],
      "affiliations": [],
      "venue": "arXiv",
      "publication_status": "preprint",
      "published_at": "2026-08-18T07:32:50Z",
      "updated_at": "2026-08-18T07:32:50Z",
      "source_kind": "arxiv",
      "source_url": "https://arxiv.org/abs/2608.17453",
      "pdf_url": "https://arxiv.org/pdf/2608.17453v1",
      "contribution_zh": "",
      "review_status": "approved",
      "reviewed_at": "2026-08-20T00:49:56Z",
      "relevance_score": 6.75,
      "degree": 0,
      "composite_weight": 0.0675
    },
    {
      "id": "paper_2608_17423",
      "name": "Prism-GRPO: Faster VLA Policy Optimization via Splitting Same-outcome Groups",
      "type": "paper",
      "description": "GRPO is increasingly used for reinforcement learning of vision-language-action (VLA) policies because, unlike PPO, it does not require training a critic. This simplification comes with a sampling cost: group-relative advantages require multiple rollouts from each scene. Under binary success rewards, groups whose rollouts all succeed or all fail have zero advantage and are discarded by dynamic sampling. These groups are especially common early in training, when most rollouts fail, wasting much of the expensive robotic rollout budget. We introduce Prism-GRPO, which augments binary outcome reward with a weighted trajectory-level execution-quality score. By splitting same-outcome groups into a quality spectrum, Prism-GRPO recovers training signal while ensuring that every success still outranks every failure. Quality scores can be derived from simulator contacts, executed actions, or visual observations, avoiding task-specific progress rewards. We prove that Prism-GRPO never increases the ",
      "group_id": "action_ground",
      "group_name": "动作对齐",
      "tags": [
        "cs.RO",
        "cs.LG",
        "vision-language-action",
        "robot"
      ],
      "paper_id": "arxiv:2608.17423",
      "title_en": "Prism-GRPO: Faster VLA Policy Optimization via Splitting Same-outcome Groups",
      "authors": [
        "Zeyun Deng",
        "Yuzhe Lu",
        "Yawei Wang",
        "Linbo Liu",
        "Qing Ping",
        "Han Ding",
        "Guande Wu",
        "Panpan Xu",
        "Jun Huan"
      ],
      "affiliations": [],
      "venue": "arXiv",
      "publication_status": "preprint",
      "published_at": "2026-08-18T06:44:16Z",
      "updated_at": "2026-08-18T06:44:16Z",
      "source_kind": "arxiv",
      "source_url": "https://arxiv.org/abs/2608.17423",
      "pdf_url": "https://arxiv.org/pdf/2608.17423v1",
      "contribution_zh": "",
      "review_status": "approved",
      "reviewed_at": "2026-08-20T00:49:56Z",
      "relevance_score": 5.5,
      "degree": 0,
      "composite_weight": 0.055
    },
    {
      "id": "paper_2608_17209",
      "name": "Teach and Grow: An Agent-Centered Architecture for General Robot Learning",
      "type": "paper",
      "description": "End-to-end vision-language-action (VLA) and world-action models offer an elegant route to general-purpose robotics, but their reliability is bounded by validated physical coverage. When an unfamiliar object, sensor, embodiment, or contact falls outside that coverage and no validated fallback exists, correcting the failure requires new robot data, a policy update, and regression testing. This recurring burden is the retraining tax. Unlike text, embodied data must often be created by operating machines. We present Teach-and-Grow Learning (TGL), an agent-centered architecture for general robot learning. In its general form, a multimodal agent turns a few successful demonstrations into reusable Skill Blocks: closed-loop behaviors for meaningful subgoals. In a new scene, the agent grounds and composes these blocks, selects learned or geometric tools, observes the physical outcome, and revises the route when execution departs from intent. A Skill Library stores executable behavior, while str",
      "group_id": "action_ground",
      "group_name": "动作对齐",
      "tags": [
        "cs.RO",
        "cs.AI",
        "cs.CV",
        "cs.LG",
        "vision-language-action",
        "robotics",
        "robot"
      ],
      "paper_id": "arxiv:2608.17209",
      "title_en": "Teach and Grow: An Agent-Centered Architecture for General Robot Learning",
      "authors": [
        "Chang Nie",
        "Zhe Liu",
        "Hesheng Wang"
      ],
      "affiliations": [],
      "venue": "arXiv",
      "publication_status": "preprint",
      "published_at": "2026-08-17T23:45:21Z",
      "updated_at": "2026-08-17T23:45:21Z",
      "source_kind": "arxiv",
      "source_url": "https://arxiv.org/abs/2608.17209",
      "pdf_url": "https://arxiv.org/pdf/2608.17209v1",
      "contribution_zh": "",
      "review_status": "approved",
      "reviewed_at": "2026-08-20T00:49:56Z",
      "relevance_score": 6.62,
      "degree": 0,
      "composite_weight": 0.0662
    },
    {
      "id": "paper_2608_17095",
      "name": "Inference-Time Attention Steering for Vision-Language-Action Driving Models",
      "type": "paper",
      "description": "Vision-language-action (VLA) driving models couple a reasoning stage with a diffusion-based trajectory decoder, but do not give a direct way to redirect attention toward safety-critical actors at inference time without retraining. We studied a bounded additive pre-softmax attention bias on the visual tokens of detector localized traffic actors on Alpamayo-R1's Qwen3-VL backbone. It is applied as a fail open forward pre-hook with no weight changes. On 50 lane-change scenarios from the Physical AI World Model Synthetic dataset. The trajectory decoder shows a monotonic dose response in the bias magnitude, separate from a paired zero bias control at every tested magnitude. It reaches $\\approx 17$\\,cm mean displacement with lateral shifts up to $\\sim 140$\\ cm at the clamp. A layer ablation places the action-relevant signal in late layers, where the effect increases with the number of hooked layers (2.0cm for the first 8 layers; 67.6cm for all 36). A per call injection audit explains why the",
      "group_id": "action_ground",
      "group_name": "动作对齐",
      "tags": [
        "cs.CV",
        "world model",
        "vision-language-action",
        "physical ai"
      ],
      "paper_id": "arxiv:2608.17095",
      "title_en": "Inference-Time Attention Steering for Vision-Language-Action Driving Models",
      "authors": [
        "Darshan Nagendra Prasad",
        "Lars Ullrich",
        "Knut Graichen"
      ],
      "affiliations": [],
      "venue": "arXiv",
      "publication_status": "preprint",
      "published_at": "2026-08-17T20:03:38Z",
      "updated_at": "2026-08-17T20:03:38Z",
      "source_kind": "arxiv",
      "source_url": "https://arxiv.org/abs/2608.17095",
      "pdf_url": "https://arxiv.org/pdf/2608.17095v1",
      "contribution_zh": "",
      "review_status": "approved",
      "reviewed_at": "2026-08-20T00:49:56Z",
      "relevance_score": 16.25,
      "degree": 0,
      "composite_weight": 0.1625
    },
    {
      "id": "paper_2608_16889",
      "name": "Don't Drop the BATON: Long-Horizon Robot Manipulation via Agentic Subtask Exploration and Transition-aware Memory",
      "type": "paper",
      "description": "Long-horizon robot manipulation chains many contact-rich skills into one multi-stage task. Vision-language-action (VLA) models increasingly master the individual skills, yet the chain still fails: errors compound beyond the policy's ability to correct, and one subtask silently constrains the next. A promising recipe freezes the VLA and puts an LLM agent in charge: it plans in language, moves in free space with analytic primitives, invokes the VLA only for contact-rich segments, and writes adaptation into language memory. Applied to long horizons, it breaks twice. (1) Competence comes from whole-task exploration at test time, whose cost is multiplicative in stages: if one stage needs T episodes, a K-stage task needs about T^K, and a failure does not reveal which stage caused it. (2) It has no representation of transitions: the VLA primitive carries an exit but no entry condition, so a subtask can succeed in a form its successor cannot use. We present BATON. Against (1), BATON makes the ",
      "group_id": "action_ground",
      "group_name": "动作对齐",
      "tags": [
        "cs.RO",
        "cs.AI",
        "cs.CV",
        "vision-language-action",
        "robot"
      ],
      "paper_id": "arxiv:2608.16889",
      "title_en": "Don't Drop the BATON: Long-Horizon Robot Manipulation via Agentic Subtask Exploration and Transition-aware Memory",
      "authors": [
        "Bingxin Xu",
        "Yuzhang Shang",
        "Emilio Ferrara"
      ],
      "affiliations": [],
      "venue": "arXiv",
      "publication_status": "preprint",
      "published_at": "2026-08-17T17:59:57Z",
      "updated_at": "2026-08-17T17:59:57Z",
      "source_kind": "arxiv",
      "source_url": "https://arxiv.org/abs/2608.16889",
      "pdf_url": "https://arxiv.org/pdf/2608.16889v1",
      "contribution_zh": "",
      "review_status": "approved",
      "reviewed_at": "2026-08-20T00:49:56Z",
      "relevance_score": 5.62,
      "degree": 0,
      "composite_weight": 0.0562
    },
    {
      "id": "paper_2608_16885",
      "name": "$τ_0$-VLA: a Hierarchical Robot Foundation Model with World-Model-Guided Test-Time Computation",
      "type": "paper",
      "description": "Long-horizon robot manipulation requires a robot to both execute individual skills reliably and sequence them coherently over extended tasks. Most hierarchical vision-language-action (VLA) models make each such decision with a single forward pass, leaving no mechanism to allocate additional computation to difficult or consequential choices. We introduce $τ_0$-VLA, a hierarchical robot foundation model that formulates high-level subtask generation as a compute-scalable inference problem through world-model-guided test-time computation. At each inference step, the high-level policy uses execution memory to generate a subtask and, when needed, searches over alternatives before committing to its output. A low-level policy then executes the generated subtask across multiple robot embodiments. The policy is trained on 40,115 hours of heterogeneous real-world data with multimodal co-training. Across in-domain and distribution-shifted settings, allocating additional test-time computation subst",
      "group_id": "action_ground",
      "group_name": "动作对齐",
      "tags": [
        "cs.RO",
        "vision-language-action",
        "robot foundation model",
        "robot"
      ],
      "paper_id": "arxiv:2608.16885",
      "title_en": "$τ_0$-VLA: a Hierarchical Robot Foundation Model with World-Model-Guided Test-Time Computation",
      "authors": [
        "Xiaowei Cai",
        "Yunuo Cai",
        "Bingao Chen",
        "Jingxiao Chen",
        "Zhi Chen",
        "Siyuan Feng",
        "Tengyu Hou",
        "Jingshun Huang",
        "Han Jiang",
        "Runkun Ju",
        "Dong Li",
        "Mingxiang Li",
        "Shaowei Li",
        "Xinchen Li",
        "Yifan Li",
        "Yi Liu",
        "Zhongyuan Liu",
        "Jianlan Luo",
        "Junwen Miao",
        "Ruiqi Ni",
        "Buqing Nie",
        "Mingjie Pan",
        "Xinlin Ren",
        "Jianheng Song",
        "Jiaxu Wang",
        "Peiqi Wang",
        "Sen Wang",
        "Xiaoyan Wang",
        "Dafeng Wei",
        "Dongming Wu",
        "Pengwei Xie",
        "Pu Yang",
        "Hangjian Ye",
        "Xiangyu Yue",
        "Jinyu Zhang",
        "Qinglin Zhang",
        "Xueyong Zhao",
        "Pengfei Zhou",
        "Yue Zhou"
      ],
      "affiliations": [],
      "venue": "arXiv",
      "publication_status": "preprint",
      "published_at": "2026-08-17T17:59:11Z",
      "updated_at": "2026-08-17T17:59:11Z",
      "source_kind": "arxiv",
      "source_url": "https://arxiv.org/abs/2608.16885",
      "pdf_url": "https://arxiv.org/pdf/2608.16885v1",
      "contribution_zh": "",
      "review_status": "approved",
      "reviewed_at": "2026-08-20T00:49:56Z",
      "relevance_score": 11.88,
      "degree": 0,
      "composite_weight": 0.1188
    },
    {
      "id": "paper_2608_16837",
      "name": "HAF: Adapting Generalist VLAs to Humanoid Whole-Body Loco-manipulation via Hierarchical Action Flow and Spectral Latent RL",
      "type": "paper",
      "description": "Humanoid robots hold great promise as general-purpose agents in human-centered environments, yet generalist vision-language-action (VLA) foundation models are not readily applicable to humanoid whole-body loco-manipulation. The high dimensionality and interdependence of humanoid motions make it challenging for conventional single-stage VLA architectures to coordinate locomotion, waist posture, and dual-arm manipulation effectively. Moreover, policies trained through offline behavior cloning can remain suboptimal during real-world deployment. Although online reinforcement learning can refine policies through real-world interaction, directly tuning large VLA backbones demands excessive computation and may introduce safety risks during real-robot exploration. To address these bottlenecks, we introduce HAF (Humanoid Adaptation Framework), a two-part framework consisting of HAF-VLA and HAF-Steer that transfers off-the-shelf generalist VLA foundation models to humanoid whole-body loco-manipu",
      "group_id": "action_ground",
      "group_name": "动作对齐",
      "tags": [
        "cs.RO",
        "cs.AI",
        "vision-language-action",
        "robot"
      ],
      "paper_id": "arxiv:2608.16837",
      "title_en": "HAF: Adapting Generalist VLAs to Humanoid Whole-Body Loco-manipulation via Hierarchical Action Flow and Spectral Latent RL",
      "authors": [
        "Langzhe Gu",
        "Chengkai Hou",
        "Meng Li",
        "Xinhua Wang",
        "Jiaming Liu",
        "Xinyuan Lv",
        "Bowei Zhang",
        "Shuanghao Bai",
        "Guangrun Li",
        "Jingyang He",
        "Gaole Dai",
        "Ziluo Ding",
        "Zhiyuan Xu",
        "Kuan Cheng",
        "Jian Tang",
        "Zhengping Che",
        "Shanghang Zhang"
      ],
      "affiliations": [],
      "venue": "arXiv",
      "publication_status": "preprint",
      "published_at": "2026-08-17T17:22:33Z",
      "updated_at": "2026-08-17T17:22:33Z",
      "source_kind": "arxiv",
      "source_url": "https://arxiv.org/abs/2608.16837",
      "pdf_url": "https://arxiv.org/pdf/2608.16837v1",
      "contribution_zh": "",
      "review_status": "approved",
      "reviewed_at": "2026-08-20T00:49:56Z",
      "relevance_score": 5.5,
      "degree": 0,
      "composite_weight": 0.055
    },
    {
      "id": "paper_2608_16697",
      "name": "FabriMAE I Trust Myself? Self-Evaluating VLA Action Generation with Markov Attention Entropy",
      "type": "paper",
      "description": "Vision-Language-Action models (VLAs) integrate visual perception, language instruction, and action generation into end-to-end policies across heterogeneous architectures. However, enabling VLAs to self-evaluate their action generation reliability without external supervision remains a major challenge. Existing methods either rely on expert annotations or estimate uncertainty only from output statistics, largely ignoring internal signals. In this work, we observe that internal visual modality entropy exhibits consistent distinctions between successful and failed tasks across heterogeneous VLAs. Although VLAs' architectures differ in their action generation, we show that they share a common latent action generation abstraction evolving under visual perception, language instruction, and state input, which we formulate as a Conditional Generative Markov Chain. Based on this formulation, we propose MAE (Markov Attention Entropy), a self-evaluation framework that directly converts internal a",
      "group_id": "action_ground",
      "group_name": "动作对齐",
      "tags": [
        "cs.AI",
        "vision-language-action"
      ],
      "paper_id": "arxiv:2608.16697",
      "title_en": "FabriMAE I Trust Myself? Self-Evaluating VLA Action Generation with Markov Attention Entropy",
      "authors": [
        "Aniri",
        "Chen Yilin",
        "Jinhe Bi",
        "Junfei Guo",
        "Donglai Ran",
        "Xu Bian",
        "Zengjie Jin",
        "Yujun Wang",
        "Yijun Tian",
        "Volker Tresp",
        "Fei Shen",
        "Tat-Seng Chua",
        "Yunpu Ma"
      ],
      "affiliations": [],
      "venue": "arXiv",
      "publication_status": "preprint",
      "published_at": "2026-08-17T15:14:53Z",
      "updated_at": "2026-08-17T15:14:53Z",
      "source_kind": "arxiv",
      "source_url": "https://arxiv.org/abs/2608.16697",
      "pdf_url": "https://arxiv.org/pdf/2608.16697v1",
      "contribution_zh": "",
      "review_status": "approved",
      "reviewed_at": "2026-08-20T00:49:56Z",
      "relevance_score": 5.0,
      "degree": 0,
      "composite_weight": 0.05
    },
    {
      "id": "paper_2608_16555",
      "name": "Co-design of Neural and Muscle Network based on Embodied Perceptron Representation",
      "type": "paper",
      "description": "Recent advances in AI technologies have enabled the advanced design of complex control policies. In contrast, focusing on the body, many robots still employ simple bodies that can limit adaptability to environments. Studies in embodied robotics have shown that well-designed bodies can partially replace the role of control and computation with physical body-environment interactions, yet such designs still depend heavily on expert intuition. There is a need for a systematic theoretical framework for body design, as well as a method for joint optimization of the body and controller. To address this, we introduce the Embodied Perceptron, a theoretical framework that unifies neural networks and physical body systems. In this view, the body itself acts as a perceptron: mechanical parameters correspond to weights, and physical nonlinearities play the role of activation functions. By representing physical constraints as weights and nonlinear properties as activation functions, a physical body ",
      "group_id": "action_ground",
      "group_name": "动作对齐",
      "tags": [
        "cs.RO",
        "embodied ai",
        "robotics",
        "robot"
      ],
      "paper_id": "arxiv:2608.16555",
      "title_en": "Co-design of Neural and Muscle Network based on Embodied Perceptron Representation",
      "authors": [
        "Siyuan Tao",
        "Yoichi Masuda",
        "Hiroyuki Nabae",
        "Masato Ishikawa"
      ],
      "affiliations": [],
      "venue": "arXiv",
      "publication_status": "preprint",
      "published_at": "2026-08-17T13:25:09Z",
      "updated_at": "2026-08-17T13:25:09Z",
      "source_kind": "arxiv",
      "source_url": "https://arxiv.org/abs/2608.16555",
      "pdf_url": "https://arxiv.org/pdf/2608.16555v1",
      "contribution_zh": "",
      "review_status": "approved",
      "reviewed_at": "2026-08-20T00:49:56Z",
      "relevance_score": 5.5,
      "degree": 0,
      "composite_weight": 0.055
    },
    {
      "id": "paper_2608_16503",
      "name": "NebulaVLA: A Dual-Frequency Vision-Language-Action Model With Guide Action for Robotic Manipulation",
      "type": "paper",
      "description": "Real-world deployment of Vision-Language-Action (VLA) models is often bottlenecked by efficiency-performance trade-offs, cross-embodiment generalization, and execution smoothness. We present NebulaVLA, an asynchronous dual-frequency architecture that decouples high-level semantic reasoning from low-level action control, optimizing computational resources and modularity. To bridge semantic gaps across heterogeneous robots, we introduce GESTURE-7, a unified language-grounded action representation. Furthermore, our Guide Action algorithm enforces kinematic continuity via mask-based smoothness constraints. Comprehensive evaluations demonstrate that NebulaVLA significantly outperforms synchronous baselines, achieving an 85.5\\% average success rate on LIBERO-Plus and accelerating action generation by \\textasciitilde 2.7$\\times$. This asynchronous design enables highly efficient and responsive control for practical robotics.",
      "group_id": "action_ground",
      "group_name": "动作对齐",
      "tags": [
        "cs.RO",
        "cs.AI",
        "vision-language-action",
        "robotics",
        "robot"
      ],
      "paper_id": "arxiv:2608.16503",
      "title_en": "NebulaVLA: A Dual-Frequency Vision-Language-Action Model With Guide Action for Robotic Manipulation",
      "authors": [
        "Cong Zhao",
        "Shuai Tian",
        "Xu Zhang",
        "Baocheng Ni",
        "Xinguo Song",
        "Xueying Sun",
        "Shu Jiang",
        "Shouchang Yang",
        "Bo Tang",
        "Jin Deng",
        "Ge Zhu",
        "YongCheng Wang",
        "Jin Xu",
        "Ri Yang"
      ],
      "affiliations": [],
      "venue": "arXiv",
      "publication_status": "preprint",
      "published_at": "2026-08-17T12:40:23Z",
      "updated_at": "2026-08-17T12:40:23Z",
      "source_kind": "arxiv",
      "source_url": "https://arxiv.org/abs/2608.16503",
      "pdf_url": "https://arxiv.org/pdf/2608.16503v1",
      "contribution_zh": "",
      "review_status": "approved",
      "reviewed_at": "2026-08-20T00:49:56Z",
      "relevance_score": 7.88,
      "degree": 0,
      "composite_weight": 0.0788
    },
    {
      "id": "paper_2608_16476",
      "name": "Exposing the Long-tail in Embodied Urban Navigation via Scalable Learning from In-the-Wild Videos",
      "type": "paper",
      "description": "Learning embodied urban navigation policies from real-world data is constrained by the cost of task-specific data collection and the limited coverage of rare yet safety-critical scenarios. To address these challenges, we present a scalable framework for learning point-goal urban navigation from web-scale in-the-wild egocentric videos while systematically exposing its long tail. The framework automatically annotates uncurated web videos with metric trajectories and structured navigation semantics, which are then used to train a vision-language-action policy for interpretable navigation planning. We characterize the long tail based on model performance and the distribution of perception-motion patterns, and employ reflection-based analysis to diagnose recurring failure modes. Experiments on web-video data and real-world urban navigation tasks demonstrate effective knowledge transfer from unconstrained videos and reveal coherent long-tail structures beyond aggregate navigation performance",
      "group_id": "action_ground",
      "group_name": "动作对齐",
      "tags": [
        "cs.RO",
        "vision-language-action"
      ],
      "paper_id": "arxiv:2608.16476",
      "title_en": "Exposing the Long-tail in Embodied Urban Navigation via Scalable Learning from In-the-Wild Videos",
      "authors": [
        "Bingyi Xia",
        "Han Bao",
        "Zhewei Chen",
        "Hanjing Ye",
        "Jingwen Yu",
        "Yuhan Pang",
        "Wenjun Xu",
        "Jiankun Wang"
      ],
      "affiliations": [],
      "venue": "arXiv",
      "publication_status": "preprint",
      "published_at": "2026-08-17T12:15:59Z",
      "updated_at": "2026-08-17T12:15:59Z",
      "source_kind": "arxiv",
      "source_url": "https://arxiv.org/abs/2608.16476",
      "pdf_url": "https://arxiv.org/pdf/2608.16476v1",
      "contribution_zh": "",
      "review_status": "approved",
      "reviewed_at": "2026-08-20T00:49:56Z",
      "relevance_score": 5.0,
      "degree": 0,
      "composite_weight": 0.05
    },
    {
      "id": "paper_2608_16222",
      "name": "HiPHI: A Large-Scale Benchmark for High-Precision Human Motion and Object-Interaction",
      "type": "paper",
      "description": "Humanoid intelligence requires learning over an extremely diverse space of whole-body motions and physically grounded interactions. However, existing embodied datasets remain fundamentally limited: internet-scale video data lack precise physical states and interaction grounding, while laboratory motion datasets provide high fidelity but only narrow behavioral coverage. This mismatch creates a critical bottleneck for scalable humanoid policy learning. We present HiPHI, a 600+ hour scale high-fidelity whole-body human motion dataset designed to systematically maximize coverage of the human motion and interaction manifold. HiPHI is theoretically guided by FrameNet, a linguistic framework organizing human primitives. Created using an optical motion capture pipeline, HiPHI provides sub-millimeter spatial marker tracking accuracy for full-body human motion and mesh-level object trajectories. We further introduce a benchmark suite evaluating motion-space diversity, interaction grounding, obje",
      "group_id": "action_ground",
      "group_name": "动作对齐",
      "tags": [
        "cs.RO",
        "cs.AI",
        "physical ai"
      ],
      "paper_id": "arxiv:2608.16222",
      "title_en": "HiPHI: A Large-Scale Benchmark for High-Precision Human Motion and Object-Interaction",
      "authors": [
        "Jiahao Ji",
        "Ji Ma",
        "Runhan Zhang",
        "Runyi Yu",
        "Wenjia Wang",
        "Weiheng Chi",
        "Qianqian Peng",
        "Weichao Yan",
        "Yongfei Gu",
        "Ye Tian",
        "Ting Wu",
        "Longwei Li",
        "Chun Yuan",
        "Ruoli Dai",
        "Lei Han"
      ],
      "affiliations": [],
      "venue": "arXiv",
      "publication_status": "preprint",
      "published_at": "2026-08-17T07:54:26Z",
      "updated_at": "2026-08-17T07:54:26Z",
      "source_kind": "arxiv",
      "source_url": "https://arxiv.org/abs/2608.16222",
      "pdf_url": "https://arxiv.org/pdf/2608.16222v1",
      "contribution_zh": "",
      "review_status": "approved",
      "reviewed_at": "2026-08-20T00:49:56Z",
      "relevance_score": 5.0,
      "degree": 0,
      "composite_weight": 0.05
    },
    {
      "id": "paper_2608_16172",
      "name": "SparkVLA: Stop-Aware Hierarchical VLA with Adaptive Action Chunking for Long-Horizon Manipulation",
      "type": "paper",
      "description": "At every re-observation point in a hierarchical Vision-Language-Action (VLA) system, two interface decisions must be made: when to terminate the current subtask and how far to execute the proposed action chunk. These decisions are mutually dependent---the optimal stopping point depends on what the executor plans to do, while the optimal execution length depends on where the subtask boundary lies---yet existing architectures evaluate them in isolation, an asymmetry neither module can overcome alone. We present SparkVLA, a stop-aware hierarchical VLA that resolves this mutual dependency by formulating both decisions as a single ranking: Stop competes against every action-prefix length in a unified candidate set, and the system selects the highest-scoring option, eliminating threshold tuning and requiring only offline ordinal preferences. An Anchor-Conditioned Context Encoding module caches a history-aware subtask anchor encoding onset-state memory and goal semantics, guiding visual-token",
      "group_id": "action_ground",
      "group_name": "动作对齐",
      "tags": [
        "cs.RO",
        "vision-language-action",
        "robot"
      ],
      "paper_id": "arxiv:2608.16172",
      "title_en": "SparkVLA: Stop-Aware Hierarchical VLA with Adaptive Action Chunking for Long-Horizon Manipulation",
      "authors": [
        "Xunyao Lei",
        "Renjun Wu",
        "Tianlin Huo",
        "Xuesong Li"
      ],
      "affiliations": [],
      "venue": "arXiv",
      "publication_status": "preprint",
      "published_at": "2026-08-17T06:43:11Z",
      "updated_at": "2026-08-17T06:43:11Z",
      "source_kind": "arxiv",
      "source_url": "https://arxiv.org/abs/2608.16172",
      "pdf_url": "https://arxiv.org/pdf/2608.16172v1",
      "contribution_zh": "",
      "review_status": "approved",
      "reviewed_at": "2026-08-20T00:49:56Z",
      "relevance_score": 5.5,
      "degree": 0,
      "composite_weight": 0.055
    },
    {
      "id": "paper_2608_16074",
      "name": "US-VLA: An Ultrasound Vision-Language-Action Model for Embodied Abdomina",
      "type": "paper",
      "description": "Artificial intelligence-assisted ultrasound scanning enhances diagnostic reliability and efficiency by providing real-time guidance for standardized image acquisition and reducing operator dependence. However, existing reinforcement learning and learning-assisted ultrasound scanning methods typically rely on carefully designed reward functions or extensive interaction data, which limits their generalization ability and stability across different devices, patient populations, and complex clinical scenarios. To address these challenges, we propose an ultrasound vision-language-action model (US-VLA) for automated ultrasound scanning that explicitly encodes clinical semantic goals and generates sequential probe manipulation actions under real-time ultrasound feedback. In particular, we first design an ultrasound-aware expert fusion module to jointly integrate ultrasound observations with auxiliary contextual information, enabling semantic ultrasound feedback to effectively guide the scanni",
      "group_id": "action_ground",
      "group_name": "动作对齐",
      "tags": [
        "cs.RO",
        "cs.CV",
        "vision-language-action"
      ],
      "paper_id": "arxiv:2608.16074",
      "title_en": "US-VLA: An Ultrasound Vision-Language-Action Model for Embodied Abdomina",
      "authors": [
        "Cheng Zhang",
        "Xingzheng Wu",
        "Guihao Yan",
        "Xifeng Hu",
        "Zhi Liu",
        "Mei Wu",
        "Qing Cai"
      ],
      "affiliations": [],
      "venue": "arXiv",
      "publication_status": "preprint",
      "published_at": "2026-08-17T04:12:21Z",
      "updated_at": "2026-08-17T04:12:21Z",
      "source_kind": "arxiv",
      "source_url": "https://arxiv.org/abs/2608.16074",
      "pdf_url": "https://arxiv.org/pdf/2608.16074v1",
      "contribution_zh": "",
      "review_status": "approved",
      "reviewed_at": "2026-08-20T00:49:56Z",
      "relevance_score": 6.25,
      "degree": 0,
      "composite_weight": 0.0625
    },
    {
      "id": "paper_2608_16556",
      "name": "DeepInsight II: One Trace from Benchmark to Robot",
      "type": "paper",
      "description": "Across a Physical AI stack, evaluation maturity is inversely aligned with deployment risk: foundation models enjoy mature, standardized harnesses, while the embodied layers on which deployment actually turns remain fragmented across benchmark-specific simulators, embodiments, and interfaces. The first DeepInsight report (v1) unified evaluation across this stack behind three abstractions---task, resource, and result---but its quantitative evidence centered on the foundation-model layer; navigation and manipulation (System 1) and whole-body control (System 0) remained simulation case studies, and physical execution was outside its empirical scope. DeepInsight II keeps that substrate fixed and quantifies the embodied half. First, it reproduces released-checkpoint references across two navigation and four manipulation benchmarks under their native protocols. Second, MotionBench places four released whole-body controllers under one workload and metric contract, then carries a qualified with",
      "group_id": "phys_engine",
      "group_name": "物理仿真引擎",
      "tags": [
        "cs.AI",
        "physical ai",
        "robot"
      ],
      "paper_id": "arxiv:2608.16556",
      "title_en": "DeepInsight II: One Trace from Benchmark to Robot",
      "authors": [
        "Siyi Li",
        "Yuchen Kang",
        "Wuliang Wang",
        "Zhengjie Zhang",
        "Jiangpin Liu",
        "Jianhao Yao",
        "Jie Chen"
      ],
      "affiliations": [],
      "venue": "arXiv",
      "publication_status": "preprint",
      "published_at": "2026-08-17T13:25:24Z",
      "updated_at": "2026-08-17T13:25:24Z",
      "source_kind": "arxiv",
      "source_url": "https://arxiv.org/abs/2608.16556",
      "pdf_url": "https://arxiv.org/pdf/2608.16556v1",
      "contribution_zh": "",
      "review_status": "approved",
      "reviewed_at": "2026-08-20T00:49:56Z",
      "relevance_score": 5.62,
      "degree": 0,
      "composite_weight": 0.0562
    },
    {
      "id": "paper_gen15embodiedfoundationmodelsareoneshotl",
      "name": "GEN-1.5: Embodied Foundation Models are One-Shot Learners",
      "type": "tech_report",
      "description": "GEN-1.5 is an embodied foundation model that learns new closed-loop robotic skills from a single 3-12 second sensorimotor demonstration through physical prompting, without gradient updates. The model supports compositional prompting, zero-shot sim-to-real transfer, human-to-robot imitation, and few-shot adaptation with 1-10 gradient steps. Generalist reports 59% average success for one-shot in-context learning and 83% after ten-step adaptation across ten physical manipulation tasks.",
      "group_id": "action_ground",
      "group_name": "动作对齐",
      "tags": [
        "embodied foundation model",
        "robot"
      ],
      "paper_id": "manual:gen15embodiedfoundationmodelsareoneshotl",
      "title_en": "GEN-1.5: Embodied Foundation Models are One-Shot Learners",
      "authors": [
        "Generalist Team"
      ],
      "affiliations": [],
      "venue": "Generalist AI Blog",
      "publication_status": "technical_report",
      "published_at": "2026-08-19T00:00:00Z",
      "updated_at": "2026-08-19T00:00:00Z",
      "source_kind": "manual",
      "source_url": "https://generalistai.com/blog/gen-1.5",
      "pdf_url": "",
      "contribution_zh": "",
      "review_status": "approved",
      "reviewed_at": "2026-08-20T01:23:35Z",
      "relevance_score": 6.75,
      "degree": 0,
      "composite_weight": 0.0675
    }
  ],
  "links": [
    {
      "source": "V_JEPA2",
      "target": "Meta_FAIR",
      "relation_type": "released_by",
      "label": "团队发布",
      "weight": 3
    },
    {
      "source": "V_JEPA2",
      "target": "Adrien_Bardes",
      "relation_type": "authored_by",
      "label": "论文作者",
      "weight": 3
    },
    {
      "source": "V_JEPA2",
      "target": "David_Fan",
      "relation_type": "authored_by",
      "label": "论文作者",
      "weight": 3
    },
    {
      "source": "V_JEPA2",
      "target": "Quentin_Garrido",
      "relation_type": "authored_by",
      "label": "论文作者",
      "weight": 3
    },
    {
      "source": "V_JEPA2",
      "target": "Russell_Howes",
      "relation_type": "authored_by",
      "label": "论文作者",
      "weight": 3
    },
    {
      "source": "V_JEPA2",
      "target": "Mojtaba_Komeili",
      "relation_type": "authored_by",
      "label": "论文作者",
      "weight": 3
    },
    {
      "source": "V_JEPA2",
      "target": "Koustuv_Sinha",
      "relation_type": "authored_by",
      "label": "论文作者",
      "weight": 3
    },
    {
      "source": "V_JEPA2",
      "target": "Yann_LeCun",
      "relation_type": "authored_by",
      "label": "论文作者",
      "weight": 3
    },
    {
      "source": "V_JEPA2",
      "target": "Michael_Rabbat",
      "relation_type": "authored_by",
      "label": "论文作者",
      "weight": 3
    },
    {
      "source": "V_JEPA2",
      "target": "Nicolas_Ballas",
      "relation_type": "authored_by",
      "label": "论文作者",
      "weight": 3
    },
    {
      "source": "V_JEPA2_1",
      "target": "Meta_FAIR",
      "relation_type": "released_by",
      "label": "团队发布",
      "weight": 3
    },
    {
      "source": "V_JEPA2_1",
      "target": "Lorenzo_Mur_Labadia",
      "relation_type": "authored_by",
      "label": "论文作者",
      "weight": 3
    },
    {
      "source": "V_JEPA2_1",
      "target": "Matthew_Muckley",
      "relation_type": "authored_by",
      "label": "论文作者",
      "weight": 3
    },
    {
      "source": "V_JEPA2_1",
      "target": "Amir_Bar",
      "relation_type": "authored_by",
      "label": "论文作者",
      "weight": 3
    },
    {
      "source": "V_JEPA2_1",
      "target": "Koustuv_Sinha",
      "relation_type": "authored_by",
      "label": "论文作者",
      "weight": 3
    },
    {
      "source": "V_JEPA2_1",
      "target": "Yann_LeCun",
      "relation_type": "authored_by",
      "label": "论文作者",
      "weight": 3
    },
    {
      "source": "V_JEPA2_1",
      "target": "Nicolas_Ballas",
      "relation_type": "authored_by",
      "label": "论文作者",
      "weight": 3
    },
    {
      "source": "V_JEPA2_1",
      "target": "Adrien_Bardes",
      "relation_type": "authored_by",
      "label": "论文作者",
      "weight": 3
    },
    {
      "source": "paper_2608_17163",
      "target": "Chelsea_Finn",
      "relation_type": "authored_by",
      "label": "论文作者",
      "weight": 3
    },
    {
      "source": "paper_2608_16859",
      "target": "Gao_Jun",
      "relation_type": "authored_by",
      "label": "论文作者",
      "weight": 3
    },
    {
      "source": "paper_2608_16859",
      "target": "Liu_Ming_Yu",
      "relation_type": "authored_by",
      "label": "论文作者",
      "weight": 3
    },
    {
      "source": "paper_2608_18077",
      "target": "Li_Yunzhu",
      "relation_type": "authored_by",
      "label": "论文作者",
      "weight": 3
    }
  ]
};
